disaster_notification/urls.py
from django.contrib import admin
from django.urls import path, include
from notification.views import upload_csv_view
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('dn_admin/', admin.site.urls),
    path('redis/', staff_member_required(include('dj_redis_panel.urls'))),
    path('', include('notification.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("upload_csv", upload_csv_view, name="upload_csv"),
    path("forecasting/", include("forecasting.urls")),
]        

forecasting/urls.py
from django.urls import path
from forecasting.views import forecasting_view

urlpatterns = [
    path("", forecasting_view, name="forecasting"),
]

notification/urls.py
from django.urls import path, include
from notification.views import dashboard_view, subscribe_view, user_alerts_view, delete_subscription_view, upload_csv_view, grab_counties_for_state, test_email_view, test_sms_view, test_alert_view

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('subscribe/', subscribe_view, name='subscribe'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_alerts/', user_alerts_view, name="user_alerts"),
    path('delete_subscription/<int:sub_id>/', delete_subscription_view, name='delete_subscription'),
    # not being used anymore
    path("upload_csv/", upload_csv_view, name="upload_csv"),
    path("ajax/get-counties/", grab_counties_for_state, name="grab_counties"),
    # test groups
    path("test_email/", test_email_view, name="test_email"),
    path("test_sms/", test_sms_view, name="test_sms"),
    path("test_alert/", test_alert_view, name="test_alert"),
]

notification/models.py
from django.db import models
from django.contrib.auth.models import User

# create your models here.
# NOAA alert API model
class NoaaAlert(models.Model):
    # stores an alert
    # uses the 'id' from the api properties as the primary key
    id = models.CharField(primary_key=True, max_length=255)
    area_desc = models.TextField()
    event = models.CharField(max_length=255)
    headline = models.TextField(null=True, blank=True)
    description = models.TextField()
    instruction = models.TextField(null=True, blank=True)
    response = models.CharField(max_length=50, null=True, blank=True)
    affected_zones = models.JSONField(default=list)
    geometry = models.JSONField(default=dict, null=True, blank=True)
    status = models.CharField(max_length=50)
    message_type = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    severity = models.CharField(max_length=50)
    certainty = models.CharField(max_length=50)
    urgency = models.CharField(max_length=50)
    sent = models.DateTimeField()
    effective = models.DateTimeField()
    onset = models.DateTimeField(null=True, blank=True)
    expires = models.DateTimeField(null=True, blank=True)
    ends = models.DateTimeField(null=True, blank=True)
    sender_name = models.CharField(max_length=255)

    # json fields for nested or variable data
    geocode = models.JSONField(default=dict)
    parameters = models.JSONField(default=dict)

    def __str__(self):
        # simple readable label for admin and logs
        return f"{self.event} ({self.severity})"

# NOT USED FOR VONAGE
# CREATED ORIGINALLY FOR GMAIL/SENDGRID SMTP METHOD - will just be hidden from user view and default value will be ''
# CARRIER_NAMES = {
#     "vtext.com": "Verizon",
#     "txt.att.net": "AT&T",
#     "tmomail.net": "T-Mobile",
#     "messaging.sprintpcs.com": "Sprint",
#     "mms.uscc.net": "US Cellular",
#     "message.alltel.com": "AllTel",
# }

# stores what area a user wants to follow for alerts
class UserAreaSubscription(models.Model):
    # holds the notification choices that the user can pick
    NOTIFY_CHOICES = [
        ("New", "Notify on new alert"),
        ("Update", "Notify on update"),
        ("Expires", "Notify before expiration"),
        ("All", "All notifications"),
    ]

    # links each subscription to a real user account
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    area = models.CharField(max_length=255)

    # already had users in the database during tests so have to put in a default space for county and state to make it work
    county = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')

    phone_number = models.CharField(max_length=20)

    # similar situation with state and county so I had to put in default parameters
    # NOT USED FOR VONAGE
    # CREATED ORIGINALLY FOR GMAIL/SENDGRID SMTP METHOD - will just be hidden from user view and default value will be ''
    carrier = models.CharField(max_length=50, default='', blank=True)

    # pulled the value like vtext.com instead of Verizon on the Alert Subscriptions page
    # def carrier_label(self):
    #     return CARRIER_NAMES.get(self.carrier, self.carrier)

    # saves what notification type the user wants
    notification_type = models.CharField(
        max_length=50,
        choices=NOTIFY_CHOICES,
        default="New",
    )

    # timestamp when created
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} -> {self.area}"


# tracks what alerts were already sent so it doesn't send the same one again
class AlertNotificationTracking(models.Model):
    # links to the user who got the alert
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # links to the noaa alert that was delivered
    alert = models.ForeignKey(NoaaAlert, on_delete=models.CASCADE)

    # saves the date and time the alert was sent out
    sent_at = models.DateTimeField(auto_now_add=True)

    # states the kind of alert like "new" or "expiring"
    alert_kind = models.CharField(max_length=20, default="New")

    def __str__(self):
        return f"{self.user.username} -> {self.alert.id}"


# storm events csv
class StormEvent(models.Model):
    # uses the event id from the csv as the primary key
    event_id = models.CharField(primary_key=True, max_length=50)
    event_type = models.CharField(max_length=100)
    state = models.CharField(max_length=50)
    county = models.CharField(max_length=100)
    begin_year = models.IntegerField(default=1)
    begin_month = models.IntegerField(default=1)
    end_year = models.IntegerField(default=1)
    end_month = models.IntegerField(default=1)
    begin_time = models.IntegerField(default=1)
    end_time = models.IntegerField(default=1)
    # added to address area_desc issue; fips will be able to match UGC data in noaaalerts
    county_fips = models.CharField(max_length=10, default='')
    state_fips = models.CharField(max_length=10, default='')

    def __str__(self):
        return f"{self.event_type} in {self.state} ({self.begin_year})"

notification/views.py
# importing os because it is needed for file paths
import os
# importing json because need to load or dump json
import json
# import runs python commands or shell commands for running manage.py commands
import subprocess
# shows html pages or redirects you also has the get_object_or_404 thing that returns 404 automatically
from django.shortcuts import render, redirect, get_object_or_404
# log in the user after registering
from django.contrib.auth import login
# decorator makes a view only work when the user is logged in
from django.contrib.auth.decorators import login_required
# for showing messages at the top of page like success or warning
from django.contrib import messages
# using Count to annotate and count rows
from django.db.models import Count
from notification.models import NoaaAlert, UserAreaSubscription, StormEvent
from notification.forms import UserAreaSubscriptionForm, UserRegistrationForm, CsvUploadForm
# sends a forbidden response when someone not allowed opens a page
from django.http import HttpResponseForbidden
# decorator so only staff can use upload page
from django.contrib.admin.views.decorators import staff_member_required
# import settings to use BASE_DIR for file paths
from django.conf import settings
# import plotly graph objects to build charts
import plotly.graph_objs as go
# plot function turns plotly chart into html to show on template
from plotly.offline import plot
# used to end json response to javascript
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from notification.tasks import send_sms_vonage, send_active_alerts_to_user_task, send_test_alert_to_user_task, format_phone_number
from django.utils import timezone
import uuid
import inspect
from django.contrib.auth.models import User

# uses fips code for user matching the county/state since area_desc is not desirable for a selector
def grab_fips(sub):
    # match row
    row = (
        StormEvent.objects
        .filter(state__iexact=sub.state, county__iexact=sub.county)
        .values("state_fips", "county_fips")
        .first()
    )

    if not row:
        return None

    # the fip code consists of two digits designated for state and three digits designated for a "zone" but for the sake of simplicity for this project I'm just going to label it "county"
    state_fips = str(row["state_fips"]).strip().zfill(2)
    county_fips = str(row["county_fips"]).strip().zfill(3)

    # combine the five digit code
    return state_fips + county_fips


# disaster events grouped by year
def grab_disaster_events_per_year():

    event_data = StormEvent.objects.values("begin_year")

    event_data = event_data.annotate(total=Count("event_id"))

    event_data = event_data.order_by("begin_year")

    return event_data


# create the raw grouped info for disaster heatmap
def grab_disaster_heatmap_data():

    # grabs begin year and begin month from StormEvent model and counts how many happened and groups by two fields
    calendar_data = (
        StormEvent.objects
        .values("begin_year", "begin_month")
        .annotate(total=Count("event_id"))
        .order_by("begin_year", "begin_month")
    )

    return calendar_data


# create a matrix for the heatmap chart used for the dashboard page
def create_heatmap_matrix():

    # grabs grouped data
    heatmap_data = grab_disaster_heatmap_data()

    years = []

    for h in heatmap_data:
        # only add if not already in list
        if h["begin_year"] not in years:
            years.append(h["begin_year"])

    years.sort()

    months = list(range(1, 13))

    # matrix
    m = []
    for _ in years:
        # making a row of zeros matching the 12 months
        empty_row = [0] * len(months)
        m.append(empty_row)

    # add matrix with data
    for row in heatmap_data:

        yr = row["begin_year"]
        mo = row["begin_month"]

        total = row["total"]

        yr_index = years.index(yr)

        mo_index = months.index(mo)

        # put the count number into that spot in matrix
        m[yr_index][mo_index] = total

    # send back the years, months, and matrix
    return years, months, m

# heatmap chart that uses the matrix from create_heatmap_matrix and turns it into a plotly heatmap
def heatmap_chart():

    years, months, h = create_heatmap_matrix()

    fig = go.Figure(
        data=go.Heatmap(
            z=h,
            x=months,
            y=years,
            colorscale="Viridis",
            colorbar=dict(title="Events"),
        )
    )

    fig.update_layout(
        title="Disaster Events Heatmap from 2015-2025 (Year vs Month)",
        xaxis=dict(
            title="Month",
        ),
        yaxis=dict(
            title="Year",
        ),
    )

    return plot(fig, output_type="div")


# main dashboard page view that displays charts when selecting a county/state
def dashboard_view(request):

    disaster_data = grab_disaster_events_per_year()

    years = []
    totals = []

    for d in disaster_data:
        years.append(d["begin_year"])
        totals.append(d["total"])

    # bar chart that is for disaster events per year
    fig1 = go.Figure(
        data=[
            go.Bar(
                x=years,
                y=totals
                )
            ],
        layout=go.Layout(
            title="Disaster Events Per Year (2015-2025)",
            yaxis=dict(
                title="Event Count",

                # max(totals) * 1.1 to get a figure above bars since it looks better like this than default
                range=[0, max(totals) * 1.1]
            )
        )
    )

    disaster_chart = plot(fig1, output_type="div")

    heatmap = heatmap_chart()

    # looks at event_type and counts how many for each one
    all_types = (
        StormEvent.objects
        .values("event_type")
        .annotate(total=Count("event_id"))
        .order_by("-total")
    )

    labels = []
    counts = []

    for t in all_types:
        labels.append(t["event_type"])
        counts.append(t["total"])

    # plotly bar char for disaster events by type
    fig_types = go.Figure(
        data=[
            go.Bar(
                x=labels,
                y=counts
                )
            ],
        layout=go.Layout(
            title="Disaster Events by Type (2015-2025)"
            ),
    )

    # max(totals) * 1.1 to get a figure above bars
    fig_types.update_yaxes(range=[0, max(totals) * 1.1])

    disaster_type_chart = plot(fig_types, output_type="div")

    # excludes test alerts since this provide little value
    alerts = NoaaAlert.objects.exclude(event__icontains='test')

    # area filter
    area = request.GET.get('area', '').strip()
    # severity filter
    severity = request.GET.get('severity', '').strip()
    # urgency filter
    urgency = request.GET.get('urgency', '').strip()

    # checks if at least one filter has some text
    any_filter = area or severity or urgency

    # if user put something in filters then filter alerts
    if any_filter:

        if area:
            alerts = alerts.filter(area_desc__icontains=area)

        # match exact severity
        if severity:
            alerts = alerts.filter(severity__iexact=severity)

        # match exact urgency
        if urgency:
            alerts = alerts.filter(urgency__iexact=urgency)

        # sort newest first and limit to 50 rows
        alerts = alerts.order_by('-sent')[:50]

    # no filters selected shows the last 5 alerts created
    else:
        alerts = alerts.order_by('-sent')[:5]

    context = {
        'heatmap': heatmap,
        'disaster_chart': disaster_chart,
        'disaster_type_chart': disaster_type_chart,
        'alerts': alerts
    }

    return render(request, 'notification/dashboard.html', context)

# grabs totals of disasters per year for a specific combination of county and state
def grab_county_yearly_data(state, county):

    st = state.lower().strip()

    ct = county.lower().strip()

    combined_data = (
        StormEvent.objects
        .filter(state__iexact=st, county__iexact=ct)
        .values("begin_year")
        .annotate(total=Count("event_id"))
        .order_by("begin_year")
    )

    return combined_data


# bar chart for the selected county over the span of the years 
def county_yearly_chart(state, county):

    yearly = grab_county_yearly_data(state, county)

    years = []
    totals = []

    for y in yearly:

        years.append(y["begin_year"])

        totals.append(y["total"])

    # bar chart using plotly
    fig = go.Figure(
        data=[
            go.Bar(
                x=years,
                y=totals,
                )
            ],
        layout=go.Layout(
            title=f"Disaster Events Per Year in {county}, {state} (2015 to 2025)",
            yaxis=dict(
                title="Count"
                )
        )
    )

    return plot(fig, output_type="div")


# grabs disaster event types and how many happened for each type
def grab_county_event_type_data(state, county):

    st = state.lower().strip()
    ct = county.lower().strip()

    # group by event_type and count how many for each type
    combined_data = (
        StormEvent.objects
        .filter(state__iexact=st, county__iexact=ct)
        .values("event_type")
        .annotate(total=Count("event_id"))
        .order_by("-total")
    )

    return combined_data


# bar chart for disaster types for when a user selects a county on user page
def county_event_type_chart(state, county):

  combined_type = grab_county_event_type_data(state, county)

  disaster_types = []
  disaster_totals = []

  for t in combined_type:
    disaster_types.append(t["event_type"])
    disaster_totals.append(t["total"])

  # use Plotly to create chart
  fig = go.Figure(
    data=[
        go.Bar(
            x=disaster_types, 
            y=disaster_totals,
            )
        ],
        layout=
            go.Layout(

notification/templates/notification/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Disaster Notifications Page</title>

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-dark bg-dark mb-4">
    <div class="container-fluid">

        <span class="navbar-brand">Disaster Notification Page</span>

        <div class="d-flex">

            <!-- dashboard link -->
            <a href="{% url 'dashboard' %}"
               class="btn btn-primary btn-sm me-2">
                Dashboard
            </a>

            <!-- subscription page link -->
            <a href="{% url 'subscribe' %}"
               class="btn btn-primary btn-sm me-2">
                Subscribe
            </a>

            <!-- personal alerts page -->
            <a href="{% url 'user_alerts' %}"
               class="btn btn-primary btn-sm me-2">
                User Alerts Page
            </a>

            <a href="{% url 'forecasting' %}"
               class="btn btn-primary btn-sm me-2">
                Forecasting
            </a>

            {% if user.is_authenticated %}

                {% if user.is_staff %}
                    <!-- only accessible for admins who are signed in -->
                    <a href="/dn_admin/" class="btn btn-primary btn-sm me-2">Admin</a>
                    <a href="{% url 'test_alert' %}" class="btn btn-warning btn-sm me-2">Test Alert</a>
                    <a href="{% url 'test_email' %}" class="btn btn-warning btn-sm me-2">Test Email</a>
                    <a href="{% url 'test_sms' %}" class="btn btn-warning btn-sm me-2">Test SMS</a>
                    <a href="/upload_csv/" class="btn btn-primary btn-sm me-2">Upload CSV</a>
                {% endif %}
>
                <form method="POST" action="{% url 'logout' %}" class="d-inline">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-sm me-2">Logout</button>
                </form>

                <!-- show username to the right of the links -->
                <span class="navbar-text me-3">
                    Logged in as <strong>{{ user.username }}</strong>
                </span>

            {% else %}
                <!-- only shows up if not logged in -->
                <a href="{% url 'login' %}" class="btn btn-success btn-sm">Login</a>
            {% endif %}
        </div>
    </div>
</nav>

<main class="container">
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

notification/templates/notification/dashboard.html
{% extends "notification/base.html" %}
{% block title %}Disaster Notification Page{% endblock %}

{% block content %}

<h1 class="mb-4">Disaster Notification Page</h1>

<!-- filter -->
<form method="get" class="row g-3 mb-4">

    <div class="col-md-4">
        <label for="area" class="form-label">Area</label>
        <input type="text" class="form-control" id="area" name="area"
               value="{{ request.GET.area }}">
    </div>

    <div class="col-md-4">
        <label for="severity" class="form-label">Severity</label>
        <select class="form-select" name="severity" id="severity">
            <option value="">All</option>
            <option value="Severe" {% if request.GET.severity == "Severe" %}selected{% endif %}>Severe</option>
            <option value="Moderate" {% if request.GET.severity == "Moderate" %}selected{% endif %}>Moderate</option>
            <option value="Minor" {% if request.GET.severity == "Minor" %}selected{% endif %}>Minor</option>
        </select>
    </div>

    <div class="col-md-4">
        <label for="urgency" class="form-label">Urgency</label>
        <select class="form-select" name="urgency" id="urgency">
            <option value="">All</option>
            <option value="Immediate" {% if request.GET.urgency == "Immediate" %}selected{% endif %}>Immediate</option>
            <option value="Expected" {% if request.GET.urgency == "Expected" %}selected{% endif %}>Expected</option>
            <option value="Future" {% if request.GET.urgency == "Future" %}selected{% endif %}>Future</option>
            <option value="Past" {% if request.GET.urgency == "Past" %}selected{% endif %}>Past</option>
            <option value="Unknown" {% if request.GET.urgency == "Unknown" %}selected{% endif %}>Unknown</option>
        </select>
    </div>

    <div class="col-12 text-end">
        <button class="btn btn-primary mt-3">Filter</button>
        <a href="{% url 'dashboard' %}" class="btn btn-secondary mt-3">Reset</a>
    </div>

</form>


{% if alerts %}
<div class="table-responsive">

    <!-- list of alerts -->
    <table class="table table-striped table-hover align-middle">
        <thead class="table-dark">
            <tr>
                <th>Event</th>
                <th>Area</th>
                <th>Severity</th>
                <th>Urgency</th>
                <th>Sent</th>
                <th>Expires</th>
                <!-- for debugging -->
                <!--<th>Geocode</th>-->
            </tr>
        </thead>

        <tbody>
        {% for alert in alerts %}
            <tr class="
                {% if alert.severity|lower == 'severe' %}table-danger
                {% elif alert.severity|lower == 'moderate' %}table-warning
                {% elif alert.severity|lower == 'minor' %}table-info
                {% endif %}
            ">
                <td>{{ alert.event }}</td>
                <td>{{ alert.area_desc }}</td>
                <td>{{ alert.severity }}</td>
                <td>{{ alert.urgency }}</td>
                <td>{{ alert.sent|date:'Y-m-d H:i' }}</td>
                <td>{{ alert.expires|date:'Y-m-d H:i' }}</td>
                <!-- for debugging -->
                 <!--<td>{{ alert.geocode }}</td>-->
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!-- maps and charts -->
<div class="mt-4 mb-4">
    {{ heatmap|safe }}
</div>

<div class="mt-4 mb-4">
    {{ disaster_chart|safe }}
</div>

<div class="mt-4 mb-4">
    {{ disaster_type_chart|safe }}
</div>

{% else %}
<div class="alert alert-success">
    No active alerts at this time
</div>
{% endif %}

{% endblock %}

notification/templates/notification/test_alert.html
{% extends "notification/base.html" %}
{% block content %}

<div class="container mt-4">

    <h2>Send Test Alert</h2>

    {% if message_sent %}
        <div class="alert alert-success">{{ message_sent }}</div>
    {% endif %}

    <form method="post" class="card p-3 shadow-sm mt-3">
        {% csrf_token %}
        <button class="btn btn-primary">Send Test Alert</button>
    </form>

</div>

{% endblock %}

notification/templates/notification/test_email.html
{% extends "notification/base.html" %}

{% block content %}
<h2>Test Email</h2>

<form method="POST">
    {% csrf_token %}

    <label for="id_to_email">To Email</label><br>
    <input type="email" id="id_to_email" name="to_email" required><br><br>

    <label for="id_subject">Subject</label><br>
    <input type="text" id="id_subject" name="subject" placeholder="Test Email"><br><br>

    <label for="id_message">Message</label><br>
    <textarea id="id_message" name="message" rows="5" cols="40" placeholder="This is a test email from Disaster Notification."></textarea><br><br>

    <button type="submit">Send Test Email</button>
</form>

{% if result %}
    <p><strong>{{ result }}</strong></p>
{% endif %}
{% endblock %}

notification/templates/notification/test_sms.html
{% extends "notification/base.html" %}

{% block content %}
<h2>Test SMS</h2>

<form method="POST">
    {% csrf_token %}

    <label>Phone Number</label>
    <input type="text" name="phone_number" required><br><br>

    <label>Notification Type</label>
    <select name="alert_kind">
        <option value="New">New</option>
        <option value="Update">Update</option>
        <option value="Expires">Expires</option>
    </select><br><br>

    <button type="submit">Send Test SMS</button>
</form>

{% if result %}
    <p><strong>{{ result }}</strong></p>
{% endif %}
{% endblock %}

notification/templates/notification/upload_csv.html
{% extends "notification/base.html" %}

{% block content %}

<h2>CSV Upload (Admin only)</h2>

{# show warning if user is not staff #}
{% if not request.user.is_staff %}
    <p style="color: red;">You do not have permission to upload files.</p>
{% else %}
<p> This page is to upload the Noaa Storm Events csv files from https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/</p>
<p> The uploads must be cleaned with the clean_csv.py file.</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.file }}
    <button type="submit">Upload</button>
</form>

{% if message %}
    <p>{{ message_sent }}</p>
{% endif %}

{% endif %}

{% endblock %}

notification/templates/notification/user_alerts.html
{% extends "notification/base.html" %}
{% load static %}

{% block content %}
<div class="container mt-4">

    <h2>Your Alert Subscriptions</h2>

    <a href="{% url 'forecasting' %}" class="btn btn-primary">
        CLICK HERE: View forecasting of disaster likelihood
    </a>

    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-info">{{ msg }}</div>
        {% endfor %}
    {% endif %}

    <!-- list of current subs -->
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <!-- removed carrier but still exists in model -->
                <!-- <th>Area</th> -->
                <th>State</th>
                <th>County</th>
                <th>Phone</th>
                <th>Notification Type</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for sub in subscriptions %}
                <tr>
                    <!-- <td>{{ sub.area }}</td> -->
                    <td>{{ sub.state }}</td>
                    <td>{{ sub.county }}</td>
                    <td>{{ sub.phone_number }}</td>
                    <td>{{ sub.get_notification_type_display }}</td>
                    <td>
                        <form action="{% url 'delete_subscription' sub.id %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">
                                delete
                            </button>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr><td colspan="7">You have no subscriptions</td></tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Active alerts from active subscriptions -->
    <hr class="my-4">

    <h3>Active Alerts in Your Subscribed Areas</h3>

    {% if active_alerts %}
    <div class="table-responsive mt-3">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <!-- removed carrier but still exists in model -->
                    <th>Event</th>
                    <!-- while this is not used for searching, it does provide value for readability for area subscribed -->
                    <th>Area</th>
                    <th>Severity</th>
                    <th>Urgency</th>
                    <th>Sent</th>
                    <th>Expires</th>
                </tr>
            </thead>

            <tbody>
            {% for alert in active_alerts %}
                <tr class="
                    {% if alert.severity|lower == 'severe' %}table-danger
                    {% elif alert.severity|lower == 'moderate' %}table-warning
                    {% elif alert.severity|lower == 'minor' %}table-info
                    {% endif %}
                ">
                    <td>{{ alert.event }}</td>
                    <!-- while this is not used for searching, it does provide value for readability for area subscribed -->
                    <td>{{ alert.area_desc }}</td>
                    <td>{{ alert.severity }}</td>
                    <td>{{ alert.urgency }}</td>
                    <td>{{ alert.sent|date:'Y-m-d H:i' }}</td>
                    <td>{{ alert.expires|date:'Y-m-d H:i' }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="alert alert-success mt-3">
        No active alerts currently
    </div>
    {% endif %}

    <!-- filter for the charts -->
    <form method="get" class="mb-3 w-50">
        <label class="form-label">Select State</label>
        <select name="state" id="graph-state" class="form-control">
            <option value="">Select State</option>
            {% for st in states %}
                <option value="{{ st }}" {% if st == selected_state %}selected{% endif %}>{{ st }}</option>
            {% endfor %}
        </select>

        <label class="form-label mt-2">Select County</label>
        <select name="county" id="graph-county" class="form-control">
            <option value="">Select County</option>
        </select>

        <button class="btn btn-secondary mt-3">Update</button>
    </form>

    {% if county_yearly_chart %}
        {{ county_yearly_chart|safe }}
    {% endif %}

    {% if county_event_type_chart %}
        {{ county_event_type_chart|safe }}
    {% endif %}

<script>
    // when a state is selected it matches the counties for it
    document.getElementById("graph-state").addEventListener("change", function () {

        let state = this.value;

        // asking backend for county list
        fetch(`/ajax/get-counties/?state=${state}`)
            .then(r => r.json())
            .then(data => {

                let countySelect = document.getElementById("graph-county");

                // reset dropdown
                countySelect.innerHTML = '<option value="">Select County</option>';

                // add county options
                data.counties.forEach(ct => {
                    let opt = document.createElement("option");
                    opt.value = ct;
                    opt.textContent = ct;
                    countySelect.appendChild(opt);
                });
            });
    });
</script>

{% endblock %}